{% set name = "edrixs" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 659aded9e628e46393858af3052af22343d2c601a7d521b0453217dc2faee683

build:
  number: 0
  skip: true  # [not unix]

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - arpack =*=mpi_openmpi_*
    - libblas * *openblas
    - numpy
    - openblas
    - openmpi
  run:
    - python
    - libblas * *openblas
    - libopenblas
    - matplotlib-base
    - mpi4py
    - numpy
    - openblas
    - openmpi
    - scipy
    - setuptools  # provides 'pkg_resources' used in the code
    - sympy

test:
  imports:
    - edrixs
  files:
    - {{ environ["RECIPE_DIR"] }}/example_2_AIM_XAS.py
  commands:
    - python {{ environ["RECIPE_DIR"] }}/example_2_AIM_XAS.py
    - mpiexec -n 2 python {{ environ["RECIPE_DIR"] }}/example_2_AIM_XAS.py

about:
  home: https://github.com/NSLS-II/edrixs
  license: BSD-3-Clause
  license_file: LICENSE
  summary: An open source toolkit for simulating RIXS spectra based on ED

extra:
  recipe-maintainers:
    - mpmdean
    - mrakitin
